name: Trillek Engine CI

on: [pull_request]

jobs:      
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, ubuntu-16.04, macOS-latest]
        arch: [x64]
        include:
          - os: windows-latest
            arch: x86
            triplet: x86-windows
            vcpkgCommitId: '6185aa76504a5025f36754324abf307cc776f3da'
          - os: windows-latest
            arch: x64
            triplet: x64-windows
            vcpkgCommitId: '6185aa76504a5025f36754324abf307cc776f3da'
          - os: ubuntu-latest
            arch: x64
            triplet: x64-linux
            vcpkgCommitId: '6185aa76504a5025f36754324abf307cc776f3da'
          - os: ubuntu-16.04
            arch: x64
            triplet: x64-linux
            vcpkgCommitId: '6185aa76504a5025f36754324abf307cc776f3da'
            compiler: gcc
            version: "7"
          - os: macOS-latest
            arch: x64
            triplet: x64-osx
            vcpkgCommitId: '6185aa76504a5025f36754324abf307cc776f3da'
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Set vcpkg's response file path used as part of cache's key.
      uses: lukka/set-shell-env@master
      with:
        VCPKGRESPONSEFILE: ${{ github.workspace }}/vcpkg_response_files/vcpkg_${{ matrix.triplet }}.txt
        VCPKGCOMMONRESPONSEFILE: ${{ github.workspace }}/vcpkg_response_files/vcpkg_common.txt
    # Linux specific
    - name: Install GCC 7 (Ubuntu 16.04 only)
      if: matrix.os == 'ubuntu-16.04'
      run: |
        sudo apt-get update
        if [ "${{ matrix.compiler }}" = "gcc" ]; then
          sudo apt-get install -y g++-${{ matrix.version }} g++-${{ matrix.version }}-multilib
          echo "::set-env name=CC::gcc-${{ matrix.version }}"
          echo "::set-env name=CXX::g++-${{ matrix.version }}"
        else
          sudo apt-get install -y clang-${{ matrix.version }} g++-multilib
          echo "::set-env name=CC::clang-${{ matrix.version }}"
          echo "::set-env name=CXX::clang++-${{ matrix.version }}"
        fi
    - name: Install os deps (Linux)
      if: runner.os == 'Linux'
      run: sudo apt-get install libgl1-mesa-dev xorg-dev libglu1-mesa-dev libxinerama-dev libxcursor-dev p7zip-full -y
    - name: Restore artifacts, or run vcpkg, build and cache artifacts
      uses: lukka/run-vcpkg@v2.1
      id: runvcpkg
      with:
        vcpkgArguments: '@${{ env.VCPKGCOMMONRESPONSEFILE }} @${{ env.VCPKGRESPONSEFILE }}'
        vcpkgDirectory: '${{ github.workspace }}/vcpkg'
        appendedCacheKey: '${{ hashFiles(env.VCPKGCOMMONRESPONSEFILE) }}${{ hashFiles(env.VCPKGRESPONSEFILE) }}'
        vcpkgGitCommitId: '${{ matrix.vcpkgCommitId }}'
    - name:  Configure cmake and build
      uses: lukka/run-cmake@master
      id: runcmake_cmd
      with:
        cmakeListsOrSettingsJson: 'CMakeListsTxtBasic'
        cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
        useVcpkgToolchainFile: true
        buildWithCMake: true
      